### PR TITLE
Convert object keys to param case

### PR DESCRIPTION
**Pull request by dword-design**
It makes sense to convert between the casing conventions. JSON uses camel case by default and SASS uses param case.

### CODE REVIEW

**Comment by dword-design** [comment]
@Regaddi Any chance to have this merged?

**Review by Regaddi — DISMISSED** [review]

**Comment by Regaddi** [comment]
Hey @dword-design,

I'm so sorry, completely forgot about this!
I'll take some short time to clean up the tests (they're currently failing, probably due to some things changed in the last year).
Will merge this soon-ish!

Thanks for your contribution 🍻

**Comment by Regaddi** [comment]
@dword-design Could you update your branch (I resolved a merge conflict via GitHub), run `yarn` locally and also commit the updated `yarn.lock` file?

**Comment by dword-design** [comment]
@Regaddi Thanks for the quick reply! I pushed yarn.lock and fixed a test.

**Review by Regaddi — APPROVED** [review]

**Comment by dword-design** [comment]
@Regaddi Thanks!

**Comment by Regaddi** [comment]
Thanks to you!

**Pull request merged**
